## ðŸ Code final attendu

name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    outputs:
      build-and-test: "L'execution du job build-and-test c'est bien passÃ©"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:ci

  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: test e2e
        id: test-e2e
        run: |
          echo "e2e ok"
          echo "confirmation=Je confirme e2e c'est bien passÃ©" >> $GITHUB_OUTPUT
    outputs:
      test-e2e: ${{ steps.test-e2e.outputs.confirmation }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-and-test, test-e2e]

    steps:
      - name: test e2e rapport
        run: |
          echo "build-and-test-output : ${{ needs.build-and-test.outputs.build-and-test }}"
          echo "test-e2e-output : ${{ needs.test-e2e.outputs.test-e2e }}"

      - name: Deploy to Development
        if: github.ref == 'refs/heads/dev'
        run: echo "ðŸš€ Deploying to DEVELOPMENT environment"

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: echo "ðŸš€ Deploying to PRODUCTION environment"
